// Data access + domain logic for admin accounts, the master secret, and the
// one-time setup state. Nodejs runtime only (hashing + Prisma).

import { prisma } from "@/lib/db";
import { hashSecret, verifySecret } from "./password";
import { normalizeMnemonic } from "./mnemonic";

// --- AdminSetting keys ---
export const SETTING_MASTER_HASH = "master_secret_hash";
export const SETTING_MASTER_SALT = "master_secret_salt";
export const SETTING_SETUP_DONE = "setup_completed_at";

/** Normalize a username: trim + lowercase (stored lowercased, unique). */
export function normalizeUsername(input: string): string {
  return String(input ?? "").trim().toLowerCase();
}

export function usernamePolicyError(username: string): string | null {
  const u = normalizeUsername(username);
  if (u.length < 3) return "El usuario debe tener al menos 3 caracteres.";
  if (u.length > 60) return "El usuario es demasiado largo.";
  if (!/^[a-z0-9._-]+$/.test(u)) {
    return "Solo letras minúsculas, números, punto, guion y guion bajo.";
  }
  return null;
}

async function getSetting(key: string): Promise<string | null> {
  const row = await prisma.adminSetting.findUnique({ where: { key } });
  return row?.value ?? null;
}

async function setSetting(key: string, value: string): Promise<void> {
  await prisma.adminSetting.upsert({
    where: { key },
    create: { key, value },
    update: { value },
  });
}

/**
 * The system is "initialized" once setup has completed. First-visitor-wins: the
 * /administrador/setup route is reachable only while this is false.
 */
export async function isInitialized(): Promise<boolean> {
  const done = await getSetting(SETTING_SETUP_DONE);
  if (done) return true;
  // defensive: if a user somehow exists, treat as initialized too
  const count = await prisma.adminUser.count();
  return count > 0;
}

export interface SetupResult {
  mnemonic: string; // shown once to the super-admin
}

/**
 * One-time bootstrap: create the first admin user and generate the 12-word
 * master secret. Idempotent-guarded — throws if already initialized (the caller
 * re-checks too, this is the last line of defense against a double submit).
 */
export async function completeSetup(opts: {
  username: string;
  password: string;
  displayName?: string;
  mnemonic: string; // generated by the caller (nodejs) and shown to the user
}): Promise<void> {
  const uname = normalizeUsername(opts.username);
  const master = hashSecret(normalizeMnemonic(opts.mnemonic));
  const pw = hashSecret(opts.password);

  await prisma.$transaction(async (tx) => {
    const existing = await tx.adminSetting.findUnique({
      where: { key: SETTING_SETUP_DONE },
    });
    const userCount = await tx.adminUser.count();
    if (existing || userCount > 0) {
      throw new Error("already-initialized");
    }
    await tx.adminUser.create({
      data: {
        username: uname,
        displayName: opts.displayName?.trim() || null,
        passwordHash: pw.hash,
        passwordSalt: pw.salt,
      },
    });
    const now = new Date().toISOString();
    await tx.adminSetting.createMany({
      data: [
        { key: SETTING_MASTER_HASH, value: master.hash },
        { key: SETTING_MASTER_SALT, value: master.salt },
        { key: SETTING_SETUP_DONE, value: now },
      ],
    });
  });
}

/** Verify a candidate master secret (12-word phrase) against the stored hash. */
export async function verifyMasterSecret(candidate: string): Promise<boolean> {
  const [hash, salt] = await Promise.all([
    getSetting(SETTING_MASTER_HASH),
    getSetting(SETTING_MASTER_SALT),
  ]);
  if (!hash || !salt) return false;
  return verifySecret(normalizeMnemonic(candidate), { hash, salt });
}

/** Rotate the master secret to a new mnemonic (super-admin action). */
export async function rotateMasterSecret(newMnemonic: string): Promise<void> {
  const master = hashSecret(normalizeMnemonic(newMnemonic));
  await setSetting(SETTING_MASTER_HASH, master.hash);
  await setSetting(SETTING_MASTER_SALT, master.salt);
}

// --- user auth / management ---

export interface AuthedUser {
  id: number;
  username: string;
  displayName: string | null;
  mustReset: boolean;
}

/** Verify username+password; returns the user on success, null otherwise. */
export async function authenticate(
  username: string,
  password: string
): Promise<AuthedUser | null> {
  const uname = normalizeUsername(username);
  const user = await prisma.adminUser.findUnique({ where: { username: uname } });
  if (!user || user.disabled) return null;
  const ok = verifySecret(password, { hash: user.passwordHash, salt: user.passwordSalt });
  if (!ok) return null;
  await prisma.adminUser.update({
    where: { id: user.id },
    data: { lastLoginAt: new Date() },
  });
  return {
    id: user.id,
    username: user.username,
    displayName: user.displayName,
    mustReset: user.mustReset,
  };
}

export async function createUser(opts: {
  username: string;
  password: string;
  displayName?: string;
}): Promise<{ id: number; username: string }> {
  const uname = normalizeUsername(opts.username);
  const pw = hashSecret(opts.password);
  const user = await prisma.adminUser.create({
    data: {
      username: uname,
      displayName: opts.displayName?.trim() || null,
      passwordHash: pw.hash,
      passwordSalt: pw.salt,
    },
    select: { id: true, username: true },
  });
  return user;
}

/** Change a user's own password (after verifying the current one). */
export async function changeOwnPassword(
  userId: number,
  currentPassword: string,
  newPassword: string
): Promise<boolean> {
  const user = await prisma.adminUser.findUnique({ where: { id: userId } });
  if (!user) return false;
  const ok = verifySecret(currentPassword, {
    hash: user.passwordHash,
    salt: user.passwordSalt,
  });
  if (!ok) return false;
  const pw = hashSecret(newPassword);
  await prisma.adminUser.update({
    where: { id: userId },
    data: { passwordHash: pw.hash, passwordSalt: pw.salt, mustReset: false },
  });
  return true;
}

/** Super-admin resets a user's password to a chosen value (sets mustReset). */
export async function adminResetPassword(
  userId: number,
  newPassword: string
): Promise<void> {
  const pw = hashSecret(newPassword);
  await prisma.adminUser.update({
    where: { id: userId },
    data: { passwordHash: pw.hash, passwordSalt: pw.salt, mustReset: true },
  });
}

export async function setUserDisabled(userId: number, disabled: boolean): Promise<void> {
  await prisma.adminUser.update({ where: { id: userId }, data: { disabled } });
}

export async function deleteUser(userId: number): Promise<void> {
  await prisma.adminUser.delete({ where: { id: userId } });
}

export async function listUsers() {
  return prisma.adminUser.findMany({
    orderBy: { username: "asc" },
    select: {
      id: true,
      username: true,
      displayName: true,
      disabled: true,
      mustReset: true,
      lastLoginAt: true,
      createdAt: true,
    },
  });
}

export async function countUsers(): Promise<number> {
  return prisma.adminUser.count();
}
